version: "3.8"

services:
  db:
    image: postgres:15
    container_name: resn_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Nandanpur@123
      POSTGRES_DB: resn_school
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
